import { describe, expect, it } from 'vitest';
import { findChains } from '../src/core/depGraph';
import { parseNpmLock, parsePnpmLock, parseYarnLock } from '../src/core/lockfile';
import type { NormalizedLock, PackageJson } from '../src/types';

/**
 * Every fixture below describes the same graph so one assertion covers them all:
 *
 *   root → a@1.0.0 → b@1.0.0 → c@1.0.0
 *   root → d@1.0.0 → c@2.0.0      (c is installed at two versions)
 */
function assertSharedGraph(lock: NormalizedLock): void {
  expect(lock.rootDependencies).toMatchObject({ a: '1.0.0', d: '1.0.0' });
  expect(new Set(lock.versionsByName.get('c'))).toEqual(new Set(['1.0.0', '2.0.0']));

  const signatures = findChains(lock, 'c')
    .map((chain) => chain.nodes.map((n) => `${n.name}@${n.version}`).join(' > '))
    .sort();
  expect(signatures).toEqual(['a@1.0.0 > b@1.0.0 > c@1.0.0', 'd@1.0.0 > c@2.0.0']);
}

const packageJson: PackageJson = {
  dependencies: { a: '^1.0.0' },
  devDependencies: { d: '^1.0.0' },
};

describe('parseNpmLock (lockfileVersion 3)', () => {
  const content = JSON.stringify({
    name: 'root',
    version: '1.0.0',
    lockfileVersion: 3,
    packages: {
      '': {
        name: 'root',
        version: '1.0.0',
        dependencies: { a: '^1.0.0' },
        devDependencies: { d: '^1.0.0' },
      },
      'node_modules/a': { version: '1.0.0', dependencies: { b: '^1.0.0' } },
      'node_modules/b': { version: '1.0.0', dependencies: { c: '^1.0.0' } },
      'node_modules/c': { version: '1.0.0' },
      'node_modules/d': { version: '1.0.0', dependencies: { c: '^2.0.0' } },
      'node_modules/d/node_modules/c': { version: '2.0.0' },
    },
  });

  it('normalizes the graph with nested resolution', () => {
    const lock = parseNpmLock(content, 'package-lock.json', {});
    expect(lock.manager).toBe('npm');
    assertSharedGraph(lock);
  });
});

describe('parsePnpmLock (lockfileVersion 9)', () => {
  const content = `lockfileVersion: '9.0'

importers:
  .:
    dependencies:
      a:
        specifier: ^1.0.0
        version: 1.0.0
    devDependencies:
      d:
        specifier: ^1.0.0
        version: 1.0.0

packages:
  a@1.0.0:
    resolution: {integrity: aaa}
  b@1.0.0:
    resolution: {integrity: bbb}
  c@1.0.0:
    resolution: {integrity: ccc}
  c@2.0.0:
    resolution: {integrity: ccc2}
  d@1.0.0:
    resolution: {integrity: ddd}

snapshots:
  a@1.0.0:
    dependencies:
      b: 1.0.0
  b@1.0.0:
    dependencies:
      c: 1.0.0
  c@1.0.0: {}
  c@2.0.0: {}
  d@1.0.0:
    dependencies:
      c: 2.0.0
`;

  it('normalizes the graph from snapshots', () => {
    const lock = parsePnpmLock(content, 'pnpm-lock.yaml');
    expect(lock.manager).toBe('pnpm');
    assertSharedGraph(lock);
  });
});

describe('parseYarnLock (classic v1)', () => {
  const content = `# THIS IS AN AUTOGENERATED FILE.
# yarn lockfile v1


a@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/a/-/a-1.0.0.tgz#hash"
  integrity sha512-aaa
  dependencies:
    b "^1.0.0"

b@^1.0.0:
  version "1.0.0"
  dependencies:
    c "^1.0.0"

c@^1.0.0:
  version "1.0.0"

c@^2.0.0:
  version "2.0.0"

d@^1.0.0:
  version "1.0.0"
  dependencies:
    c "^2.0.0"
`;

  it('normalizes the graph using package.json for root deps', () => {
    const lock = parseYarnLock(content, 'yarn.lock', packageJson);
    expect(lock.manager).toBe('yarn');
    assertSharedGraph(lock);
  });
});

describe('parseYarnLock (berry v2+)', () => {
  const content = `# This file is generated by running "yarn install".

__metadata:
  version: 8
  cacheKey: 10c0

"a@npm:^1.0.0":
  version: 1.0.0
  resolution: "a@npm:1.0.0"
  dependencies:
    b: "npm:^1.0.0"
  languageName: node
  linkType: hard

"b@npm:^1.0.0":
  version: 1.0.0
  resolution: "b@npm:1.0.0"
  dependencies:
    c: "npm:^1.0.0"
  languageName: node
  linkType: hard

"c@npm:^1.0.0":
  version: 1.0.0
  resolution: "c@npm:1.0.0"
  languageName: node
  linkType: hard

"c@npm:^2.0.0":
  version: 2.0.0
  resolution: "c@npm:2.0.0"
  languageName: node
  linkType: hard

"d@npm:^1.0.0":
  version: 1.0.0
  resolution: "d@npm:1.0.0"
  dependencies:
    c: "npm:^2.0.0"
  languageName: node
  linkType: hard
`;

  it('normalizes the graph, stripping the npm: protocol', () => {
    const lock = parseYarnLock(content, 'yarn.lock', packageJson);
    assertSharedGraph(lock);
  });
});
